# Generated by Django 5.1.2 on 2024-11-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='image',
            field=models.ImageField(default='images/none/default.jpg', upload_to='images'),
        ),
    ]
